### ISSUE TITLE
Problem when switch to development sandbox mode

### ISSUE THREAD

**Issue by yapkahfung123** [RevenueMonster/rm-php-sdk#12]
Hi there, when i try to switch to mode to sandbox which is  'isSandbox' => true, it throwing this error, and i had double check all of my config was correct.

`Fatal error: Uncaught RevenueMonster\SDK\Exceptions\ApiException: Invalid client in /home/anthubcom/public_html/portal/vendor/revenuemonster/sdk/src/RevenueMonster.php:81 Stack trace: #0 /home/anthubcom/public_html/portal/vendor/revenuemonster/sdk/src/RevenueMonster.php(61): RevenueMonster\SDK\RevenueMonster->oauth() #1 /home/anthubcom/public_html/portal/classes-payment/LogicRevenueMonster.class.php(35): RevenueMonster\SDK\RevenueMonster->__construct(Array) #2 /home/anthubcom/public_html/portal/apps/agent/topup-payment-gateway-debug.php(53): LogicRevenueMonster->__construct(Array, true) #3 /home/anthubcom/public_html/portal/include/router.inc.php(124): include_once('/home/anthubcom...') #4 /home/anthubcom/public_html/portal/include/router.inc.php(81): find_route('agent', 'topup-payment-g...') #5 /home/anthubcom/public_html/portal/include/init.inc.php(18): require_once('/home/anthubcom...') #6 /home/anthubcom/public_html/portal/index.php(13): require_once('/home/anthubcom...') #7 {main} thrown in /home/anthubcom/public_html/portal/vendor/revenuemonster/sdk/src/RevenueMonster.php on line 81`

**Comment by si3nloong** [comment]
Hi @yapkahfung123, sandbox and production client are different, you can use production account to use in sandbox environment. If you want to test on staging, make sure you create your client in https://sb-merchant.revenuemonster.my/developer/applications
